language: node_js
node_js:
  - "node"
script:
  - echo "Deploy"
install:
  - npm install
  - cd functions
  - npm install
  - cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "todolist-one"