language: node_js
node_js:
  - "node"
script:
  - echo "Deploy"
install:
  - npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "todolist-one"